volumes:
  mysqldata:
  nginx:

networks:
  my-network:
    driver: bridge

services:
  nysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - my-network
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dbadmin'
      MYSQL_PASSWORD: 'P@$$Word123'
      MYSQL_ROOT_PASSWORD: 'P@$$word123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    image: php:7.3-fpm-alpine
    volumes:
     - ./app:/app